- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/context/ProjectContextChangeHandler.java
- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/organizationalunit/RepoAddedToOrganizationalUnitEvent.java
- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/social/RepoAddedToOrganizationaUnitEventAdapter.java
Just a typo fix.
Still the pull requests for kie-wb-common and kie-wb-distributions depends on this.
> Bug 1254907 - Items of project explorer are not refreshed automatically

- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/wizard/pages/RepositoryInfoPageViewImpl.java
Use changehandler instead of keyup
> Fix repository name autofill

- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataCreator.java
- guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/MetadataCreatorTest.java
See https://issues.jboss.org/browse/GUVNOR-2399
This is the corollary of https://github.com/droolsjbpm/guvnor/pull/260 for 6.4.x.
(cherry picked from commit 5d48a98d7fd12b8344778801aaf81a6380d5d6fa)
> [6.4.x] GUVNOR-2399: Errors retrieving LockInfo

- guvnor-webapp/pom.xml
> Page Table extract

- guvnor-inbox/guvnor-inbox-backend/pom.xml
- guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity.java
- guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity_InboxEntrySecurityTestTest.java
(cherry picked from commit c181908753e20512bad67c342d32c4ae6af13277)
> [master] Bug 1324596 - [GSS] [6.2.z] 6.2.2 unable to open/edit some assets with specific user

- guvnor-inbox/guvnor-inbox-backend/pom.xml
- guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity.java
- guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity_InboxEntrySecurityTestTest.java
https://bugzilla.redhat.com/show_bug.cgi?id=1324592
This is now a release blocker.
Targeting 6.4.x first, since couldn't get the super dev mode to work in master.
> [6.4.x] Bug 1324596 - [GSS] [6.2.z] 6.2.2 unable to open/edit some assets with specific user

- guvnor-inbox/guvnor-inbox-backend/pom.xml
- guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity.java
- guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity_getInboxEntryRepositoryTest.java
- guvnor-inbox/guvnor-inbox-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
https://bugzilla.redhat.com/show_bug.cgi?id=1324596
Almost the same as master and 6.4.x
Since 6.3.x is frozen. I am not sure if this goes in, but the patch will be done against the 6.3.x. So placing this here for a PR review.
(cherry picked from commit c181908753e20512bad67c342d32c4ae6af13277)
> [6.3.x] Bug 1324596 - [GSS] [6.2.z] 6.2.2 unable to open/edit some assets with specific user

- guvnor-project/guvnor-project-backend/pom.xml
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplCreateTest.java
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/TestAppSetup.java
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/TestProjectService.java
- guvnor-project/guvnor-project-backend/src/test/resources/META-INF/beans.xml
- guvnor-project/guvnor-project-backend/src/test/resources/logback-test.xml
- guvnor-test-utils/pom.xml
- guvnor-test-utils/src/main/java/org/guvnor/test/CDITestSetup.java
- guvnor-test-utils/src/main/java/org/guvnor/test/GuvnorTestAppSetup.java
- guvnor-test-utils/src/main/java/org/guvnor/test/TestFileSystem.java
- guvnor-test-utils/src/main/java/org/guvnor/test/TestIdentityFactory.java
- guvnor-test-utils/src/main/java/org/guvnor/test/WeldJUnitRunner.java
- guvnor-test-utils/src/main/resources/META-INF/beans.xml
- guvnor-test-utils/src/test/java/org/guvnor/test/WeldJUnitRunnerTest.java
- guvnor-test-utils/src/test/resources/logback-test.xml
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/173
> Fixes after Weld 1.x -> 2.x upgrade

- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/service/RepositoryStructureServiceImpl.java
- guvnor-project/guvnor-project-api/pom.xml
- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/context/ProjectContext.java
- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectService.java
- guvnor-project/guvnor-project-api/src/test/java/org/guvnor/common/services/project/context/ProjectContextTest.java
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/AbstractProjectService.java
- guvnor-rest/guvnor-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
- guvnor-rest/guvnor-rest-backend/src/test/java/org/guvnor/rest/backend/JobRequestHelperCreateProjectTest.java
- guvnor-rest/guvnor-rest-backend/src/test/resources/META-INF/beans.xml
- guvnor-webapp/src/main/java/org/guvnor/server/ProjectServiceImpl.java
Ticket for this branch is here: https://bugzilla.redhat.com/show_bug.cgi?id=1316566
Same as in master. Had to do some small adjustments to make it fit into 6.3.x.
(cherry picked from commit 21536e2b85d46a938f842d27f70164cedcb5dfd7)
https://github.com/droolsjbpm/guvnor/pull/286
https://github.com/droolsjbpm/kie-wb-common/pull/310
https://github.com/droolsjbpm/drools-wb/pull/144
https://github.com/droolsjbpm/jbpm-console-ng/pull/365
https://github.com/droolsjbpm/kie-wb-distributions/pull/229
> [6.3.x] Bug 1316566 - User can not create projects in any other repository than master

- guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/InboxPageRowBuilder.java
- guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/InboxPageRowBuilderTest.java
This should, of course, wait for the proper BZ acks, before any potential merge happens.
> BZ1331073 - fix uncaught exception(s) causing the eternal loading

- guvnor-asset-mgmt/guvnor-asset-mgmt-api/src/main/java/org/guvnor/asset/management/model/RepositoryStructureModel.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-api/src/main/java/org/guvnor/asset/management/service/RepositoryStructureService.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/pom.xml
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/service/ManagedStatusUpdater.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/service/RepositoryStructureModelLoader.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/service/RepositoryStructureServiceImpl.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/test/java/org/guvnor/asset/management/backend/service/ManagedStatusUpdaterTest.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/test/java/org/guvnor/asset/management/backend/service/RepositoryStructureModelLoaderTest.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/test/java/org/guvnor/asset/management/backend/service/RepositoryStructureServiceImplTest.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/test/java/org/guvnor/asset/management/backend/service/TestAppSetup.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/test/resources/META-INF/beans.xml
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/conf/RepositoryConfigurationPresenter.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/release/ReleaseConfigurationPresenter.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructurePresenter.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/test/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructurePresenterTest.java
- guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/TestAppSetup.java
- guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity_InboxEntrySecurityTestTest.java
- guvnor-inbox/guvnor-inbox-backend/src/test/resources/META-INF/beans.xml
- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/model/Project.java
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ResourceResolver.java
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplCreateTest.java
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/POMServiceImplLoadTest.java
- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/impl/git/GitRepository.java
- guvnor-test-utils/src/main/java/org/guvnor/test/TestTempFileSystem.java
https://issues.jboss.org/browse/GUVNOR-2486
https://github.com/droolsjbpm/kie-wb-common/pull/356
> GUVNOR-2486 : Project structure screen is not refreshed properly after changes in branch selection

- guvnor-asset-mgmt/guvnor-asset-mgmt-api/src/main/java/org/guvnor/asset/management/model/RepositoryStructureModel.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-api/src/main/java/org/guvnor/asset/management/service/RepositoryStructureService.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/service/RepositoryStructureServiceImpl.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/pom.xml
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/conf/RepositoryConfigurationPresenter.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/conf/RepositoryConfigurationViewImpl.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/project/structure/widgets/RepositoryStructureDataPresenter.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/project/structure/widgets/RepositoryStructureDataView.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/project/structure/widgets/RepositoryStructureDataViewImpl.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/release/ReleaseConfigurationPresenter.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/release/ReleaseConfigurationViewImpl.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/ActionHistory.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/HasModel.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/QueryDeletePopup.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryManagedStatusUpdater.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructureContext.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructureMenu.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructurePresenter.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructureTitle.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructureView.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructureViewImpl.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructureViewImpl.ui.xml
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/test/java/org/guvnor/asset/management/client/editors/project/structure/widgets/RepositoryStructureDataPresenterTest.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/test/java/org/guvnor/asset/management/client/editors/repository/structure/ActionHistoryTest.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/test/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryManagedStatusUpdaterTest.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/test/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructureContextTest.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/test/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructurePresenterTest.java
https://issues.jboss.org/browse/GUVNOR-2522
Related:
https://github.com/droolsjbpm/kie-wb-common/pull/369
While fixing the actual bug. I had doubts about RepositoryStructureServices.load(Repository,Branch) and branch not always being set up. I tried to change the code so that all the possible scenarios where load is used are safe.
While there RepositoryConfigurationPresenter had quite a lot in it. So moved few parts to new classes.
> GUVNOR-2522 : NPE after entering authoring perspective / creating new project

- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
- guvnor-structure/guvnor-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java
Fix + test
@mswiderski Can you verify please?
> GUVNOR-2565: NullPointerException when deleting repository using REST API

- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/pom.xml
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/command/ListCommitsCommand.java
- guvnor-inbox/guvnor-inbox-backend/pom.xml
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/pom.xml
- guvnor-project/guvnor-project-backend/pom.xml
- guvnor-project/guvnor-project-builder/pom.xml
- guvnor-rest/guvnor-rest-backend/pom.xml
- guvnor-services/guvnor-services-backend/pom.xml
- guvnor-structure/guvnor-structure-backend/pom.xml
- guvnor-test-utils/pom.xml
* upgrade several JEE Spec deps
> Fixes after IP BOM 7.0.0.CR4 upgrade

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectRepositoryResolver.java
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/GAVPreferencesLoader.java
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/GAVPreferencesLoaderTest.java
- guvnor-project/guvnor-project-client/pom.xml
- guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/POMEditorPanel.java
- guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/ProjectEntryPoint.java
- guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/util/ApplicationPreferences.java
- guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/POMEditorPanelTest.java
- guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/ProjectEntryPointTest.java
- guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/util/ApplicationPreferencesTest.java
This PR adds a new system property that allows users to edit GAV information when it has a parent GAV.
> RHBRMS-2476: Allow users to edit project's GAV information in business central Project Editor when it has a parent

- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/service/RepositoryStructureModelLoader.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/test/java/org/guvnor/asset/management/backend/service/RepositoryStructureModelLoaderTest.java
See https://issues.jboss.org/browse/GUVNOR-2598
> GUVNOR-2598: NPE when creating a Project in a Repository cloned via REST

- guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/security/ProjectTreeProvider.java
- guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/security/ProjectTreeProviderTest.java
- guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/organizationalunit/OrganizationalUnitTreeProviderTest.java
- guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/repositories/RepositoryTreeProviderTest.java
Fix + tests
@manstis Can you review please?
> UF-333: Stored values are not correctly presented 

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/builder/service/BuildService.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/backend/validation/GenericValidator.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/validation/model/ValidationMessage.java
See https://issues.jboss.org/browse/GUVNOR-2503 and https://github.com/droolsjbpm/kie-wb-common/pull/421
> GUVNOR-2503: Asset screen Validate-button should use incremental builder

- guvnor-organizationalunit-manager/src/main/java/org/guvnor/organizationalunit/manager/client/editor/popups/EditOrganizationalUnitPopup.ui.xml
https://issues.jboss.org/browse/GUVNOR-2646
Missing bits for the previous commit.
> GUVNOR-2646 : [ALL LANG] Unlocalized strings in 'Add or Edit New Organizational Unit' dialog.

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/builder/service/BuildService.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/backend/validation/GenericValidator.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/validation/model/ValidationMessage.java
See https://issues.jboss.org/browse/GUVNOR-2503
Mirror from: https://github.com/droolsjbpm/guvnor/pull/346 (using JDK 7)
> [6.5.x] GUVNOR-2503: Asset screen Validate-button should use incremental builder

- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/file/upload/AbstractFileServlet.java
- guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/file/upload/AbstractFileServletTest.java
See https://issues.jboss.org/browse/GUVNOR-2636
> GUVNOR-2636: [Decision Table Spreadsheet] uploading new version causes error

- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/file/upload/AbstractFileServlet.java
- guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/file/upload/AbstractFileServletTest.java
See https://issues.jboss.org/browse/GUVNOR-2636
> [6.5.x] GUVNOR-2636: [Decision Table Spreadsheet] uploading new version causes error

- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/GitMetadata.java
- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/GitMetadataStore.java
- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/impl/metadata/GitMetadataImpl.java
- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitMetadataStoreImpl.java
- guvnor-structure/guvnor-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitMetadataImplStoreTest.java
The goal is to have the possibility to fork any git repository inside the niogit directory.
To complete the goal we need:
* Separate git repositories into different directories. Those directories are named like the Organizational Units.
* Create a Fork command that copy all the content of the repository to fork and add the reference to the internal path of the origin repository.
* Write information about fork so we can track where those forks are, how many forks has those repositories, etc.
> [UF-403] Fork and Mirror

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/builder/service/BuildService.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/backend/validation/GenericValidator.java
See https://issues.jboss.org/browse/RHBPMS-4275
> [6.5.x] RHBPMS-4275: Guided Decision Table: XLS can not be validated

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/builder/service/BuildService.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/backend/validation/GenericValidator.java
See https://issues.jboss.org/browse/GUVNOR-2690
> GUVNOR-2690: Guided Decision Table: XLS can not be validated

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectServiceCore.java
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/AbstractProjectService.java
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/AbstractProjectServiceTest.java
See https://issues.jboss.org/browse/GUVNOR-2683
> GUVNOR-2683: Test Scenarios: Objects added into previously white listed packages are not updated.

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectServiceCore.java
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/AbstractProjectService.java
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/AbstractProjectServiceTest.java
See https://issues.jboss.org/browse/GUVNOR-2683
> [6.5.x] GUVNOR-2683: Test Scenarios: Objects added into previously white listed packages are not updated.

- guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/java/org/guvnor/m2repo/utils/FileNameUtilities.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/GuvnorM2Repository.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2RepoServiceImpl.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2RepositoryServiceImplTest.java
6.5.x version of https://github.com/droolsjbpm/guvnor/pull/373
> GUVNOR-2724: M2RepoService allows retrieving contents of arbitrary files

- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/PullRequest.java
- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/PullRequestAlreadyExistsException.java
- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/PullRequestStatus.java
- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/RepositoryNotFoundException.java
- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/impl/PullRequestImpl.java
See See https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-all-build-master/478/console
(There are other failures too, but this was the first I encountered)
> [UF-408]: Pull Request Service added - Add missing @Portable annotations

- guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/java/org/guvnor/m2repo/utils/FileNameUtilities.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/GuvnorM2Repository.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2RepoServiceImpl.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2RepositoryServiceImplTest.java
@manstis same as already merged master and 6.5.x. Awaits ACK....
> [6.4.x] GUVNOR-2724: M2RepoService allows retrieving contents of arbitrary files

- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataServiceImpl.java
- guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/MetadataServiceImplTest.java
@bbrodt would like this change to make his life easier.
> Move injection to constructor for Bob Brodt

- guvnor-ala/guvnor-ala-build-maven/pom.xml
- guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/config/MavenDependencyConfig.java
- guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/config/impl/MavenDependencyConfigImpl.java
- guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/executor/MavenBuildExecConfigExecutor.java
- guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/executor/MavenDependencyConfigExecutor.java
- guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/model/MavenBinary.java
- guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/model/impl/MavenProjectBinaryImpl.java
- guvnor-ala/guvnor-ala-build-maven/src/test/java/org/guvnor/ala/build/maven/executor/MavenDependencyConfigExecutorTest.java
- guvnor-ala/guvnor-ala-build-maven/src/test/resources/logback-test.xml
- guvnor-ala/guvnor-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/WildflyRuntimeTest.java
Allows new step in the pipeline to resolve a Maven dependency as binary
> Maven dependency resolver

- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerItem.java
- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerViewImpl.java
- guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerViewImplTest.java
See https://issues.jboss.org/browse/GUVNOR-2807
The issue was simple; the UI was changed to use i18n but the check for "lazy expansion" not.
Unit Testing the fix proved more troublesome.
> GUVNOR-2807: File Explorer in Admin view freezes when a project is extended

- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryBuilder.java
- guvnor-structure/guvnor-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperTest.java
* Introduce "replaceIfExists" option to allow starting with a fresh git repository
> Workbench "import example dialog": Embed stock example repositories

- guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/java/org/guvnor/m2repo/security/MavenRepositoryPagedJarTableFeatures.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/resources/org/guvnor/m2repo/GuvnorM2RepoEditorAPI.gwt.xml
- guvnor-m2repo-editor/guvnor-m2repo-editor-client/pom.xml
- guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/M2RepoEditorPresenter.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/editor/MavenRepositoryPagedJarTable.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/test/java/org/guvnor/m2repo/client/editor/MavenRepositoryPagedJarTableTest.java
See https://issues.jboss.org/browse/RHBRMS-2736
This is the corollary of https://github.com/droolsjbpm/guvnor/pull/407 for 6.5.x
> [6.5.x] RHBRMS-2736: [GSS] (6.4.z) Unable to download JAR by Users without admin role

- guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/java/org/guvnor/m2repo/security/MavenRepositoryPagedJarTableFeatures.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/resources/org/guvnor/m2repo/GuvnorM2RepoEditorAPI.gwt.xml
- guvnor-m2repo-editor/guvnor-m2repo-editor-client/pom.xml
- guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/M2RepoEditorPresenter.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/editor/MavenRepositoryPagedJarTable.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/test/java/org/guvnor/m2repo/client/editor/MavenRepositoryPagedJarTableTest.java
See https://issues.jboss.org/browse/GUVNOR-2858
This PR delegats the check to add the "download" button to ```AuthorizationManager```
It also includes a little refactoring to improve testability.
> GUVNOR-2858: Unable to download JAR by Users without admin role

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/preferences/GAVPreferences.java
- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/preferences/GeneralPreferences.java
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectRepositoryResolverImpl.java
- guvnor-project/guvnor-project-client/pom.xml
- guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/preferences/ProjectScopedResolutionStrategySupplier.java
- guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/POMEditorPanelTest.java
- guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/preferences/ProjectScopedResolutionStrategySupplierTest.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/preferences/DefaultWorkbenchPreferenceScopeResolutionStrategies.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/preferences/WorkbenchPreferenceScopeResolutionStrategies.java
- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/preferences/WorkbenchPreferenceScopeResolutionStrategiesProducer.java
Preference API changed, so it's a simple package refactor.
Dependes on: https://github.com/uberfire/uberfire/pull/605
> UF-459: Preference API Refactor

- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationFactoryImpl.java
- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationServiceImpl.java
https://issues.jboss.org/browse/GUVNOR-2872
See
org.kie.workbench.common.services.datamodel.backend.server.DataModelServiceConstructorTest
for unit test.
> Add constructors to allow use without requiring CDI

- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/validation/model/ValidationMessage.java
* Add copy constructor to ValidationMessage
> PLANNER-736: Workbench: Prevent user from creating multiple @PlanningSolution data objects

- guvnor-rest/guvnor-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
- guvnor-rest/guvnor-rest-backend/src/test/java/org/guvnor/rest/backend/JobRequestHelperTest.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/test/TestService.java
https://issues.jboss.org/browse/GUVNOR-2922
- https://github.com/kiegroup/drools-wb/pull/423
- https://github.com/kiegroup/guvnor/pull/423
> GUVNOR-2922 : [Test Scenario] Reporting panel is not shown

- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/AbstractProjectService.java
- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/AbstractProjectServiceTest.java
GUVNOR-2952: [Library] Breadcrumb should be updated when the opened project is renamed
GUVNOR-2947: [Library] Fix create new asset dropdown overflow and order items alphabetically
GUVNOR-2946: [Library] Show business process, guided decision table, data object first at the empty project screen (and order the rest alphabetically).
GUVNOR-2951: [Library] Add option to create new folder/package in a project.
> Library issues fix

- guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/InboxBackendImpl.java
- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigurationServiceImpl.java
- guvnor-structure/guvnor-structure-backend/src/test/java/org/guvnor/structure/backend/config/ConfigurationServiceImplTest.java
https://issues.jboss.org/browse/GUVNOR-2893
> [6.5.x] GUVNOR-2893 [GSS] (6.4.z) Slow InboxBackendImpl.recordUserEditEvent()

- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerItem.java
- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerViewImpl.java
- guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerViewImplTest.java
See https://issues.jboss.org/browse/RHBPMS-4640
- cherry-pick: https://github.com/kiegroup/guvnor/pull/397
- Before:
- After:
> [6.5.x] RHBPMS-4640: Unable to load repository in business central in administration

- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/helpers/HttpPostHelper.java
https://issues.jboss.org/browse/GUVNOR-2971
> GUVNOR-2971 : [GSS](6.4.x)Artifact repository upload functionality allows malicious code injection

- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/helpers/HttpPostHelper.java
https://issues.jboss.org/browse/GUVNOR-2971
(cherry picked from commit 228a9969ea2f50d16a5c0541caa2c465d5f135a5)
> [6.5.x] GUVNOR-2971 : [GSS](6.4.x)Artifact repository upload functionality allows malicious code injection

- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/metadata/model/Metadata.java
- guvnor-services/guvnor-services-api/src/test/java/org/guvnor/common/services/shared/metadata/model/MetadataTest.java
This is the corollary of https://github.com/kiegroup/guvnor/pull/436 for 7.0.x
> [7.0.x] GUVNOR-2976: Guided Decision Table Graph: Save operation saves changes just to selected graph

- guvnor-services/guvnor-services-backend/pom.xml
- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/social/SocialTimelineRulesQuery.java
- guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/social/SocialTimelineRulesQueryTest.java
@psiroky Would you mind approving (fixes cause of Selenium test failures)
> Fix Social Activities ksession instantiation.

- guvnor-services/guvnor-services-backend/pom.xml
- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/social/SocialTimelineRulesQuery.java
- guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/social/SocialTimelineRulesQueryTest.java
(cherry picked from commit fd36a1c881a89ab58664ad9142abc6a3d15cd1e0)
@psiroky FYI
> [7.0.x] Fix Social Activities ksession instantiation.

- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/structure/RepositoryStructureMenu.java
- guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/test/java/org/guvnor/asset/management/client/editors/repository/wizard/CreateRepositoryWizardTest.java
- guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/client/editors/repository/clone/CloneRepositoryPresenterTest.java
Add tests for checking that CONFIGURE_REPOSITORY permissions enables/disables Managed Repository option in New repository and Clone repository dialogs.
> Add config repository permission tests for create and clone dialogs

- guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/events/AfterEditOrganizationalUnitEvent.java
Cherry picked from master (https://github.com/kiegroup/guvnor/pull/442).
> [7.0.x] GUVNOR-3009: [Library] Create a root screen on library (tiles) to navigate and create Organizational Units (Teams)

- guvnor-ala/guvnor-ala-spi/src/main/java/org/guvnor/ala/util/VariableInterpolation.java
- guvnor-ala/guvnor-ala-spi/src/test/java/org/guvnor/ala/util/VariableInterpolationTest.java
- adds the ability of recurse into the super class hirerachy for finding the interfaces, instead of just querying the parent class.
> Fixes for AppFormer

- guvnor-rest/guvnor-rest-backend/src/build/revapi-config.json
Hi, @psiroky,
same as #448, but for 7.0.x.
Marian
> [7.0.x] Change revapi-config.json comment to be more general

- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/advnavigator/TreeNavigator.java
- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerItem.java
- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerViewImpl.java
- guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerViewImplTest.java
This is a code refactor due to a uberfire tree improvement. Should be merged with this [PR of uberfire](https://github.com/AppFormer/uberfire/pull/708) ; as they have compilation dependencies.
For more information see [this ticket](https://issues.jboss.org/browse/JBPM-5862).
Thanks.
> JBPM-5862: Stunner - Diagram tree explorer improvements.

- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/advnavigator/TreeNavigator.java
- guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerViewImplTest.java
@ederign @romartin these are the new files with comments deleted. See comments on [this PR](https://github.com/kiegroup/guvnor/pull/451)
Thanks.
> JBPM-5862: deleted comments

- guvnor-structure/guvnor-structure-client/pom.xml
- guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/StructureEntryPoint.java
- guvnor-structure/guvnor-structure-client/src/main/resources/org/guvnor/structure/GuvnorStructureClient.gwt.xml
See https://issues.jboss.org/browse/UF-517
> UF-517: Bootstrap Selector CSS overriding Patternfly Selector CSS

- guvnor-inbox/guvnor-inbox-backend/pom.xml
- guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/InboxBackend.java
- guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/InboxBackendImpl.java
- guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/InboxPreferencesLoader.java
- guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/InboxBackendDisablingPropertyTest.java
- guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/InboxBackendImplTest.java
https://issues.jboss.org/browse/GUVNOR-3095
https://github.com/kiegroup/guvnor/pull/454
https://github.com/kiegroup/kie-wb-distributions/pull/530
> [6.5.x] GUVNOR-3095 : Make 6.4.x Inbox optional

- guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/RepositoryResolverTestUtils.java
> AF-558: rename ReleaseId in order to avoid problems with Drools/jBPM

- guvnor-project/guvnor-project-builder/pom.xml
- guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/IncrementalBuilderExecutorManager.java
- guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/IncrementalBuilderExecutorManagerFactoryImpl.java
- guvnor-project/guvnor-project-builder/src/test/java/org/guvnor/common/services/builder/IncrementalBuilderExecutorManagerFactoryImplTest.java
- guvnor-rest/guvnor-rest-backend/pom.xml
- guvnor-rest/guvnor-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java
description: https://github.com/AppFormer/uberfire/pull/761
> [AF-559]: replaced managedExecutorService with ExecutorService

- guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/preferences/scope/GlobalPreferenceScope.java
- guvnor-project/guvnor-project-api/src/test/java/org/guvnor/common/services/project/preferences/scope/GlobalPreferenceScopeTest.java
- guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/preferences/GuvnorPreferenceScopes.java
Hello @paulovmr , would you mind review this PR?
Thanks!
> GUVNOR-3311: Move the Global preferences scope from kie-wb-commons to guvnor

- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/LocalArtifactRepository.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/repositories/LocalArtifactRepositoryTest.java
> [AF-590]: Fixed loop when trying to get root dir in LocalArtifactRepository

- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataServiceImpl.java
- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedAttributesUtil.java
- guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedAttributesView.java
- guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedAttributesUtilTest.java
@manstis This is just a cherry pick of https://github.com/kiegroup/guvnor/pull/473. Would you mind merging? Thanks in advance.
> [7.3.x] AF-547: VFS commit batch broken (#473)

- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/LocalArtifactRepository.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/repositories/LocalArtifactRepositoryTest.java
@porcelli Cherry-picked from #494.
> [AF-590]: Fixed loop when trying to get root dir in LocalArtifactRepository (#494)

- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectConfigurationContentHandler.java
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectRepositoriesContentHandler.java
- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigGroupMarshaller.java
(cherry picked from commit d791e66fe71a44fbcda6825fea9391a62ddd8458)
> RHBRMS-2784 - XStream: DoS when unmarshalling void type (#483)

- guvnor-ala/guvnor-ala-openshift/guvnor-ala-openshift-provider/src/test/java/org/guvnor/ala/openshift/dns/OpenShiftNameService.java
- guvnor-ala/guvnor-ala-openshift/guvnor-ala-openshift-provider/src/test/java/org/guvnor/ala/openshift/executor/OpenShiftExecutorTest.java
- guvnor-ala/guvnor-ala-openshift/guvnor-ala-openshift-provider/src/test/java/org/guvnor/ala/openshift/executor/OpenShiftMavenDeployer.java
- guvnor-ala/guvnor-ala-openshift/guvnor-ala-openshift-provider/src/test/resources/jboss-image-streams.json
fix docker registry location in streams
https://issues.jboss.org/browse/GUVNOR-3025
> fix docker registry location in streams

- guvnor-ala/guvnor-ala-openshift/guvnor-ala-openshift-provider/src/main/java/org/guvnor/ala/openshift/access/OpenShiftClient.java
GUVNOR-3025: fix logic in kie server container deployment
https://issues.jboss.org/browse/GUVNOR-3025
> GUVNOR-3025: fix logic in kie server container deployment

- guvnor-rest/guvnor-rest-backend/src/test/java/org/guvnor/m2repo/preferences/ArtifactRepositoryPreferenceTest.java
Test checking default values of Artifact Repository preferences (same way as in [FileExportsPreferencesTest](https://github.com/AppFormer/uberfire/blob/master/uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-api/src/test/java/org/uberfire/ext/editor/commons/file/exports/FileExportsPreferencesTest.java) in Uberfire).
> add test for Artifact Repository preferences

- guvnor-ala/guvnor-ala-ui/guvnor-ala-ui-api/src/main/java/org/guvnor/ala/ui/handler/AbstractProviderHandlerRegistry.java
- guvnor-ala/guvnor-ala-ui/guvnor-ala-ui-api/src/test/java/org/guvnor/ala/ui/handler/AbstractProviderHandlerRegistryTest.java
- guvnor-ala/guvnor-ala-ui/guvnor-ala-ui-client/src/main/java/org/guvnor/ala/ui/client/ProvisioningManagementPerspective.java
- guvnor-ala/guvnor-ala-ui/guvnor-ala-ui-client/src/main/java/org/guvnor/ala/ui/client/provider/ProviderPresenter.java
- guvnor-ala/guvnor-ala-ui/guvnor-ala-ui-client/src/main/java/org/guvnor/ala/ui/client/wizard/NewProviderWizard.java
- guvnor-ala/guvnor-ala-ui/guvnor-ala-ui-client/src/test/java/org/guvnor/ala/ui/client/ProvisioningManagementPerspectiveTest.java
- guvnor-ala/guvnor-ala-ui/guvnor-ala-ui-client/src/test/java/org/guvnor/ala/ui/client/provider/ProviderPresenterTest.java
- guvnor-ala/guvnor-ala-ui/guvnor-ala-ui-client/src/test/java/org/guvnor/ala/ui/client/wizard/NewProviderWizardTest.java
(cherry picked from commit a05b787cbe13346309e4eb575b8c0fbc0ad12e42)
> GUVNOR-3485: Provider type shouldn't be available for selection if the UI components are not present (#512)

- guvnor-ala/guvnor-ala-build-maven/src/test/java/org/guvnor/ala/build/maven/executor/MavenDependencyConfigExecutorTest.java
- guvnor-ala/guvnor-ala-docker-provider/src/test/java/org/guvnor/ala/docker/executor/DockerExecutorTest.java
- guvnor-ala/guvnor-ala-services-rest/src/test/java/org/guvnor/ala/services/rest/tests/RestPipelineImplTest.java
- guvnor-ala/guvnor-ala-services-rest/src/test/java/org/guvnor/ala/services/rest/tests/RestRuntimeProvisioningImplTest.java
- guvnor-ala/guvnor-ala-spi/src/test/java/org/guvnor/ala/marshalling/BaseMarshallerTest.java
- guvnor-ala/guvnor-ala-wildfly/guvnor-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/WildflyExecutorTest.java
- guvnor-ala/guvnor-ala-wildfly/guvnor-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/WildflyRuntimeTest.java
- guvnor-ala/guvnor-ala-wildfly/guvnor-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/requirement/NotWindowsRequirement.java
- guvnor-ala/guvnor-ala-wildfly/guvnor-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/requirement/RequiresNotWindows.java
- guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/GuvnorM2Repository.java
Some minor fixes for Windows-specific test failures.
> Windows test stabilization

- guvnor-project/guvnor-project-backend/pom.xml
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectConfigurationContentHandler.java
- guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectRepositoriesContentHandler.java
- guvnor-structure/guvnor-structure-backend/pom.xml
- guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/config/ConfigGroupMarshaller.java
See BSIG emails regarding XStream.
> Use XStreamUtils.createTrustingXStream(..) helper

- guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/ObservableClassFile.java
- guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/ObservableJavaFile.java
- guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/ObservablePOMFile.java
- guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/ResourceChangeObservableFile.java
- guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/ResourceChangeObserver.java
- guvnor-project/guvnor-project-builder/src/test/java/org/guvnor/common/services/builder/ObservableClassFileTest.java
- guvnor-project/guvnor-project-builder/src/test/java/org/guvnor/common/services/builder/ObservableJavaFileTest.java
- guvnor-project/guvnor-project-builder/src/test/java/org/guvnor/common/services/builder/ObservablePOMFileTest.java
See https://issues.jboss.org/browse/GUVNOR-3521
> GUVNOR-3521: DRL Editor: Declared types are ignored by the Fact Types list
