guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/service/RepositoryStructureServiceImpl.java
guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/wizard/CreateRepositoryWizard.java
guvnor-structure/guvnor-structure-api/src/main/java/org/guvnor/structure/repositories/EnvironmentParameters.java
guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryFactoryImpl.java
guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryServiceImpl.java
guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelper.java
guvnor-structure/guvnor-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitRepositoryFactoryHelperTest.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/repository/clone/CloneRepositoryPresenter.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/repository/create/CreateRepositoryForm.java

See https://bugzilla.redhat.com/show_bug.cgi?id=1263454
The problem was that the ```CreateRepositoryForm``` did not set the repository to be "unmanaged".
I fixed that here (and moved the constants in ```EnvironmentParameters``` to the ```-api``` module to allow re-use of the constants on both the server and client - as it had been duplicated in ```CreateRepositoryWizard```).

BZ1263454: Unable to create Project in cloned Git Repository

---

guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/command/MavenDeployProjectCommand.java
guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/main/java/org/guvnor/asset/management/backend/service/RepositoryStructureServiceImpl.java
guvnor-asset-mgmt/guvnor-asset-mgmt-backend/src/test/java/org/guvnor/asset/management/backend/service/RepositoryStructureServiceImplTest.java
guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/editors/repository/wizard/CreateRepositoryWizard.java
guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/java/org/guvnor/asset/management/client/i18n/Constants.java
guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/main/resources/org/guvnor/asset/management/client/i18n/Constants.properties
guvnor-asset-mgmt/guvnor-asset-mgmt-client/src/test/java/org/guvnor/asset/management/client/editors/repository/wizard/CreateRepositoryWizardTest.java
guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/model/GAV.java
guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/model/ProjectRepositories.java
guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectRepositoryResolver.java
guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/AbstractDeleteProjectObserverBridge.java
guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/AbstractProjectRepositoriesServiceImpl.java
guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/GAVCheckPreferencesLoader.java
guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectRepositoryResolverImpl.java
guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/AbstractDeleteProjectObserverBridgeTest.java
guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/AbstractProjectRepositoriesServiceImplTest.java
guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/GAVCheckPreferencesLoaderTest.java
guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/ProjectRepositoryResolverImplTest.java
guvnor-webapp/src/main/java/org/guvnor/server/DeleteProjectObserverBridge.java
guvnor-webapp/src/main/java/org/guvnor/server/ProjectRepositoriesServiceImpl.java

See https://issues.jboss.org/browse/BPMSPL-252
This PR includes updates requested by QE following their testing. It also moves a couple of WebBeans (WAS) unfriendly ```<? extends Project>``` from ```guvnor``` to ```<KieProject>``` in ```kie-wb-common```.
Branch name retained (yes, I know @psiroky it's not ideal) to be consistent and support reconciliation of all changes made for the feature.

BPMSPL-252: [GSS-RFE] Ability to check duplicate of ReleaseId (GroupId, ArtifactId and Version) with existing projects. Updates following QE feedback.

---

guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/RepositoryResolverTestUtils.java

See https://github.com/droolsjbpm/drools/commit/2f9b2c740c7601fa7f811d6ac2d5d48fcbb97583
This changed the API for MavenRepository. This PR simply changes guvnor to use the revised API.

DROOLS-1057: Change kie-ci API to make it able to deploy on any remote repository. Fixes to guvnor following change to kie-ci API

---

guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/MetadataCreatorTest.java

- Fixed MetadataCreatorTest compilation issues on jdk 1.6.

MetadataCreatorTest doesn't compile on jdk 1.6

---

guvnor-inbox/guvnor-inbox-backend/pom.xml

This fixes the currently failing test `InboxEntrySecurity_InboxEntrySecurityTestTest` (huh, that's a weird name :))

guvnor-inbox-backend: add test-scoped servlet-api to fix faling test

---

guvnor-asset-mgmt/guvnor-asset-mgmt-backend/pom.xml

Part of an ensemble:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/226
https://github.com/droolsjbpm/drools/pull/815
https://github.com/droolsjbpm/optaplanner/pull/200
https://github.com/droolsjbpm/jbpm/pull/487
https://github.com/droolsjbpm/droolsjbpm-integration/pull/509
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/29
https://github.com/droolsjbpm/guvnor/pull/328
https://github.com/droolsjbpm/drools-wb/pull/209
https://github.com/droolsjbpm/jbpm-designer/pull/302
https://github.com/droolsjbpm/jbpm-console-ng/pull/432
https://github.com/droolsjbpm/kie-wb-distributions/pull/303

[DROOLS-1216] exclude commons-logging and use jcl-over-slf4j instead

---

guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/model/Dependencies.java
guvnor-project/guvnor-project-api/src/test/java/org/guvnor/common/services/project/model/DependenciesTest.java

This PR adds a method that retrieves compile dependencies. As "compile" is the default scope, this PR makes dependencies without scope be handled as a compile dependency.

RHBPMS-3997: [GSS](6.3.x) Project dependencies are not retained in BPM Suite 6.3.0

---

guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/model/Dependencies.java
guvnor-project/guvnor-project-api/src/test/java/org/guvnor/common/services/project/model/DependenciesTest.java

This PR adds a method that retrieves compile dependencies. As "compile" is the default scope, this PR makes dependencies without scope be handled as a compile dependency.

[6.4.x] RHBPMS-3997: [GSS](6.3.x) Project dependencies are not retained in BPM Suite 6.3.0

---

guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectRepositoryResolver.java
guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/GAVPreferencesLoader.java
guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/GAVPreferencesLoaderTest.java
guvnor-project/guvnor-project-client/pom.xml
guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/POMEditorPanel.java
guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/ProjectEntryPoint.java
guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/util/ApplicationPreferences.java
guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/POMEditorPanelTest.java
guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/ProjectEntryPointTest.java
guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/util/ApplicationPreferencesTest.java

This PR adds a new system property that allows users to edit GAV information when it has a parent GAV.

[6.5.x] RHBRMS-2476: Allow users to edit project's GAV information in business central Project Editor when it has a parent

---

guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectRepositoryResolver.java
guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/GAVPreferencesLoader.java
guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/GAVPreferencesLoaderTest.java
guvnor-project/guvnor-project-client/pom.xml
guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/POMEditorPanel.java
guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/ProjectEntryPoint.java
guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/util/ApplicationPreferences.java
guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/POMEditorPanelTest.java
guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/ProjectEntryPointTest.java
guvnor-project/guvnor-project-client/src/test/java/org/guvnor/common/services/project/client/util/ApplicationPreferencesTest.java

This PR adds a new system property that allows users to edit GAV information when it has a parent GAV.

[6.4.x] RHBRMS-2477: Allow users to edit project's GAV information in business central Project Editor when it has a parent

---

guvnor-asset-mgmt/guvnor-asset-mgmt-project/src/main/filtered-resources/kjar/pom.xml

* required by Nexus to pass release validation rules
@manstis could you please quickly check this? It should hopefully the last thing missing now.

[RHBRMS-2447] add missing required metainfo into asset-mgmt-project POM

---

guvnor-asset-mgmt/guvnor-asset-mgmt-project/src/main/filtered-resources/kjar/pom.xml

* required by Nexus to pass release validation rules
@manstis could you please quickly check this? It should hopefully the last thing missing now.

[RHBRMS-2490] add missing required metainfo into asset-mgmt-project POM

---

guvnor-project/guvnor-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/ProjectRepositoryResolverImplTest.java

Following discussion on IRC and [this](https://github.com/droolsjbpm/drools/commit/7b09586871606f29d0a84e8b1fd19a04acb4d530) updated tests accordingly.

Ensure MavenSettings is reinitialised after tests. Switch to use of static property name

---

guvnor-structure/guvnor-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/git/GitMetadataStoreImpl.java
guvnor-structure/guvnor-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/git/GitMetadataImplStoreTest.java

@manstis this solves the problem for: _java.lang.IllegalArgumentException: Parameter named 'origin' should be not null!_
I've added a test also, to check that behavior.

[UF-403]: Fix added to solve origin null parameter problem

---

guvnor-project/guvnor-project-api/src/main/java/org/guvnor/common/services/project/preferences/GAVPreferences.java

Fix GWT's SDM complaints about not using literals in ```System.getProperty(..)```
Further to https://github.com/droolsjbpm/guvnor/pull/394 SDM failed to compile with the error:
```
[ERROR] Errors in 'org/guvnor/common/services/project/preferences/GAVPreferences.java'
[ERROR] Line 42: Only string constants may be used as property name in System.getProperty()
[ERROR] Errors in 'org/guvnor/common/services/project/preferences/GAVPreferences.java'
[ERROR] Line 47: Only string constants may be used as property name in System.getProperty()
```
Reverting to using literals.

Use literal property names

---

guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/executor/MavenBuildExecConfigExecutor.java
guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/executor/MavenDependencyConfigExecutor.java
guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/model/MavenBinary.java
guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/model/impl/MavenBinaryImpl.java
guvnor-ala/guvnor-ala-build-maven/src/main/java/org/guvnor/ala/build/maven/model/impl/MavenProjectBinaryImpl.java
guvnor-ala/guvnor-ala-build-maven/src/test/java/org/guvnor/ala/build/maven/executor/MavenDependencyConfigExecutorTest.java
guvnor-ala/guvnor-ala-build-maven/src/test/java/org/guvnor/ala/build/maven/executor/MavenProjectConfigExecutorTest.java
guvnor-ala/guvnor-ala-wildfly-provider/src/main/java/org/guvnor/ala/wildfly/config/impl/ContextAwareWildflyRuntimeExecConfig.java
guvnor-ala/guvnor-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/WildflyRuntimeTest.java

Add GAV attributes: artifactId, version and groupId to resolved MavenBinary.
Resolve MavenBinary absolute path at the executor level, allowing reuse of both MavenBinaryImpl and MavenProjectBinaryImpl at Wildfly exec stage.

Maven binary, add GAV properties and absolute path

---

guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/repository/edit/RepositoryEditorPresenter.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/repository/edit/RepositoryEditorView.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/repository/list/RepositoryItemPresenter.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/repository/list/RepositoryItemViewImpl.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/resources/i18n/CommonConstants.java
guvnor-structure/guvnor-structure-client/src/main/resources/org/guvnor/structure/client/resources/i18n/CommonConstants.properties
guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/client/editors/repository/edit/RepositoryEditorPresenterTest.java
guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/client/editors/repository/list/RepositoriesPresenterTest.java
guvnor-structure/guvnor-structure-client/src/test/java/org/guvnor/structure/client/editors/repository/list/RepositoryItemPresenterTest.java

See https://issues.jboss.org/browse/GUVNOR-2813
This PR adds a "notification" for when the URI is copied. It does not address the use of Flash which is up for debate (see the original [JIRA](https://issues.jboss.org/browse/RHBPMS-4123) ).

GUVNOR-2813: Not possible to copy repository URL in Repository Editor

---

guvnor-rest/guvnor-rest-backend/pom.xml
guvnor-rest/guvnor-rest-backend/src/build/revapi-config.json

Hi, @psiroky,
here is a revapi plugin for  guvnor-rest/guvnor-rest-backend module. It just checks REST endpoint called ProjectResource. There is again this bug in revapi, so 2 of 3 ignores are actually false-negatives.
Thanks,
Marian

Add revapi plugin

---

guvnor-ala/guvnor-ala-build-maven/src/test/java/org/guvnor/ala/build/maven/executor/RepositoryVisitorTest.java

So I noticed a test failure on master was caused by failure to download GWT 2.8.0-rc1. Though the error was probably due to network flakiness, we shouldn't be relying on that GWT version anywhere and I think the source was from this test using an outdated playground repo.
This change points the test to my fork of the appformer-playground which is currently being maintained. I also noticed several other tests pointing to Mauricio's forks of "drools-workshop" that we might need to update in the future.

Don't reference out-of-date playground repository in Guvnor ALA test.

---

guvnor-rest/guvnor-rest-backend/src/build/revapi-config.json

Hi,
this PR is related to droolsjbpm/droolsjbpm-build-bootstrap#393. Revapi config JSON file was divided into filter and ignores parts.
Marian

Split revapi configuration into filter and ignores

---

guvnor-ala/guvnor-ala-wildfly-provider/pom.xml
guvnor-ala/guvnor-ala-wildfly-provider/src/main/java/org/guvnor/ala/wildfly/config/WildflyRuntimeConfiguration.java
guvnor-ala/guvnor-ala-wildfly-provider/src/main/java/org/guvnor/ala/wildfly/config/impl/ContextAwareWildflyRuntimeExecConfig.java
guvnor-ala/guvnor-ala-wildfly-provider/src/main/java/org/guvnor/ala/wildfly/executor/WildflyRuntimeExecExecutor.java
guvnor-ala/guvnor-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/ContextAwareWildflyRuntimeExecConfigTest.java

Allow WildflyRuntimeExecConfig to consume either a maven binary or a path to the deployable file.
Allow redeploy strategy to be defined via input

JBPM-5714 - Extend  WildflyRuntimeExecConfig options customization via pipeline input

---

guvnor-ala/guvnor-ala-wildfly-provider/pom.xml
guvnor-ala/guvnor-ala-wildfly-provider/src/main/java/org/guvnor/ala/wildfly/access/impl/WildflyAccessInterfaceImpl.java
guvnor-ala/guvnor-ala-wildfly-provider/src/test/java/org/guvnor/ala/wildfly/executor/tests/WildflyAccessInterfaceImplTest.java

Use default for port (8080) and management (9990) port if not provided.

Avoid NumberFormatException if optional Wildfly port not provided

---

guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/metadata/model/Metadata.java
guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataBuilder.java
guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataCreator.java
guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataServiceImpl.java
guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedAttributesView.java
guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedFileAttributes.java
guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/MetadataCreatorTest.java
guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedFileAttributesViewTest.java

* Introduce GeneratedFileAttributesView
Useful to mark a file as "generated" and react accordingly on its processing. The file can be generated as a consequence of an action (e.g. creating a Planning Solution in OptaPlanner domain editor, etc.).
Part of:
https://github.com/droolsjbpm/guvnor/pull/421
https://github.com/droolsjbpm/drools-wb/pull/413
https://github.com/droolsjbpm/optaplanner-wb/pull/138

PLANNER-704: Workbench: scoreHolder global can only be of org.optaplanner.core.api.score.holder.ScoreHolder type (or subclass)

---

guvnor-ala/guvnor-ala-distribution/pom.xml

The dependency tree of the guvnor-ala-distribution needs a serious
review. We should be able to get rid of the Swarm deps altogether
(and use the plugin config) as they just pollute the dep. tree.
Should be merged together with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/417

Exclude org.wildfly.swarm:bootstrap to avoid duplicated classes

---

guvnor-ala/guvnor-ala-spi/src/main/java/org/guvnor/ala/pipeline/execution/PipelineExecutor.java

- Removes unnecessary recursive invocation in the PipelineExecutor that was doing nothing.
See that the pipeline execution loop is based on the !context.isFinished so recursive invocation is not neccesary.

GUVNOR-2933: Guvnor ALA integration

---

guvnor-services/guvnor-services-api/src/main/java/org/guvnor/common/services/shared/metadata/model/Metadata.java
guvnor-services/guvnor-services-api/src/test/java/org/guvnor/common/services/shared/metadata/model/MetadataTest.java

See https://issues.jboss.org/browse/GUVNOR-2976
This PR reinstates https://github.com/kiegroup/guvnor/commit/8e3676faa6e3790caaa7bf872f8c40db0a0c180f
which was inadvertently removed by https://github.com/kiegroup/guvnor/commit/f2cce32a65946a203b385667a64aeed51ee9d1b0

GUVNOR-2976: Guided Decision Table Graph: Save operation saves changes just to selected graph

---

guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/InboxBackend.java
guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/InboxBackendImpl.java
guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/InboxServiceImpl.java
guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/MailboxService.java
guvnor-inbox/guvnor-inbox-backend/src/main/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity.java
guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/InboxBackendImplTest.java
guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurityTest.java
guvnor-inbox/guvnor-inbox-backend/src/test/java/org/guvnor/inbox/backend/server/security/InboxEntrySecurity_InboxEntrySecurityTestTest.java

See https://issues.jboss.org/browse/RHBRMS-2792
@tkobayas Hi, you could try this change locally on Tomcat.
It removes injection of "User" to a method parameter that can be correctly provided from the client.
If it solves the issue we can merge into our 6.5.x.

[6.5.x] RHBRMS-2792: [GSS] (6.4.z): WELD-001303 No active contexts for scope type javax.enterprise.context.RequestScoped in Tomcat

---

guvnor-rest/guvnor-rest-backend/src/build/revapi-config.json

Hi, @psiroky,
this is only a minor change to the revapi-config.json file, since these files are no more only on master branch, but on 7.0.x as well.
Marian

Change revapi-config.json comment to be more general

---

guvnor-m2repo-editor/guvnor-m2repo-editor-api/pom.xml
guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/java/org/guvnor/m2repo/model/JarListPageRow.java
guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/java/org/guvnor/m2repo/preferences/ArtifactRepositoryPreference.java
guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/resources/org/guvnor/m2repo/GuvnorM2RepoEditorAPI.gwt.xml
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/pom.xml
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/ArtifactImpl.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/GuvnorM2Repository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2RepoServiceImpl.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/ArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/DistributionManagementArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/FileSystemArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/LocalArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/JarPathTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2RepositoryServiceImplTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-client/pom.xml
guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/M2RepoEditorEntryPoint.java
guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/resources/i18n/M2Constants.java
guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/resources/i18n/M2RepoEditorConstants.java
guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/resources/org/guvnor/m2repo/GuvnorM2RepoEditorClient.gwt.xml
guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/resources/org/guvnor/m2repo/client/resources/i18n/M2Constants.properties

Add some classes to help GuvnorM2Repository add more repositories easily. 
An ArtifactRepository interface was created son every new kind of repository should extend it to be part of GuvnorM2Repositories. 
Right now the behaviour remains the same but this let us add new FileSystem repositories or remote repositories just adding a new instance of them to GuvnorM2Repository.
It also has a Preference class so we can configure it from Workbench.

[GUVNOR-2996]: Different Repositories added to separate logic into independent components

---

guvnor-ala/guvnor-ala-distribution/src/test/java/org/guvnor/ala/services/tests/PipelineEndpointsTestIT.java
guvnor-ala/guvnor-ala-distribution/src/test/java/org/guvnor/ala/services/tests/RuntimeEndpointsTestIT.java

@manstis @porcelli @krisv @mbiarnes 
This is the PR for the two failing tests that are failng in guvnor-ala-distribution. As discussed by email the "best" option is to ignore then since nobody will use the guvnor-ala-distribution stuff at least until the 7.1 and let the 7.0.0.Final be.
This is the 7.0.x counter part for the https://github.com/kiegroup/guvnor/pull/452

Ignore Guvnor ALA failing tests in guvnor-ala-distribution

---

guvnor-rest/guvnor-rest-backend/src/build/revapi-config.json

Hi, @psiroky,
I have cleaned revapi ignores since we have a new Final version.
Marian

Clean revapi-config after 7.0.0.Final release

---

guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/archive/ArchiveServlet.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerPresenter.java
pom.xml

Enable findbugs-maven-plugin to fail the build when serious bug has been identified.
At the same time fixing 2 issues identified by the plugin.
(The configuration of the plugin can be found in [droolsjbpm-build-bootstrap/pom.xml](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L1165-L1182) and has been already fine-tuned by QE to only fail the build in cases where it's almost certain there's a bug (as you can see in the issues fixed).
@manstis wdyt?

Enable findbugs.failOnViolation

---

guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/M2RepoEditorEntryPoint.java
guvnor-organizationalunit-manager/src/main/java/org/guvnor/organizationalunit/manager/client/OrganizationalUnitManagerEntryPoint.java
guvnor-project/guvnor-project-client/src/main/java/org/guvnor/common/services/project/client/ProjectEntryPoint.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/StructureEntryPoint.java
guvnor-structure/guvnor-structure-client/src/main/java/org/guvnor/structure/client/editors/repository/clone/CloneRepositoryPresenter.java

Replace @AfterInitialization methods with @PostConstruct so that
startup RPC calls can be grouped into a single payload.

AF-546: Reduce startup time of AppFormer apps and workbenches

---

guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/java/org/guvnor/m2repo/preferences/ArtifactRepositoryPreference.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/pom.xml
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/GuvnorM2Repository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2RepoServiceImpl.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/helpers/HttpGetHelper.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/helpers/HttpPutHelper.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/ArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/ArtifactRepositoryFactory.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/DistributionManagementArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/FileSystemArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/LocalArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/JarPathTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2RepositoryServiceImplTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/resources/i18n/M2Constants.java
guvnor-m2repo-editor/guvnor-m2repo-editor-client/src/main/resources/org/guvnor/m2repo/client/resources/i18n/M2Constants.properties
guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/POMServiceImpl.java
guvnor-project/guvnor-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectRepositoryResolverImpl.java
guvnor-project/guvnor-project-builder/pom.xml
guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/IncrementalBuilderExecutorManager.java
guvnor-project/guvnor-project-builder/src/main/java/org/guvnor/common/services/builder/IncrementalBuilderExecutorManagerFactoryImpl.java
guvnor-rest/guvnor-rest-backend/pom.xml
guvnor-rest/guvnor-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java

- Improvements on M2 Repositories. Now you can configure some of them through Preference API
- Some beans converted into WorkspaceScoped beans (https://github.com/AppFormer/uberfire/pull/718)
- It also exist a WorkspaceScoped Repository but it's disabled by default because other devs needs to be done before It can be used, but It is basically a repository that is going to be used by a Workspace to store artifacts, and those artifacts can only be seen my that workspace.

[UF-506]: WorkspaceScoped beans

---

guvnor-m2repo-editor/guvnor-m2repo-editor-api/src/main/java/org/guvnor/m2repo/preferences/ArtifactRepositoryPreference.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/pom.xml
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/GuvnorM2Repository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/M2RepoServiceImpl.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/ArtifactRepositoryProducer.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/ArtifactRepositoryService.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/DistributionManagementArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/FileSystemArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/LocalArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/NullArtifactRepository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/main/java/org/guvnor/m2repo/backend/server/repositories/Repository.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/GuvnorM2RepositoryTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/JarPathTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/M2RepositoryServiceImplTest.java
guvnor-m2repo-editor/guvnor-m2repo-editor-backend/src/test/java/org/guvnor/m2repo/backend/server/repositories/ArtifactRepositoryServiceTest.java

This is the new Artifact Repositories infrastructure. It replaces the previous one with some injectable repositories.
There are some important components:
**ArtifactRepository**: This is the interface that every repository should implement. As you can see not all the repositories have to implement all the method, for instance the DistributionManagement repository is just an abstraction for the parameters that are in _pom.xm_
**@Repository**: Is the qualifier it should have every repository. 
**ArtifactRepositoryProducer**: Produces all the repositories. You can add more repositories there. It uses ArtifactRepositoryPreferences to know if the repository is enabled and to configure repositories paths.
**ArtifactRepositoryService**: Concentrates all repositories in one place. Automatically …

[UF-516]: WorkspaceScoped repositories

---

guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/MetadataServiceImpl.java
guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedAttributesUtil.java
guvnor-services/guvnor-services-backend/src/main/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedAttributesView.java
guvnor-services/guvnor-services-backend/src/test/java/org/guvnor/common/services/backend/metadata/attribute/GeneratedAttributesUtilTest.java

Add 'generated' metadata attribute only for files that have actually been generated - this avoids generating dot files for non-generated files (which will likely be > 90 % cases).
Part of:
https://github.com/kiegroup/guvnor/pull/473
https://github.com/AppFormer/uberfire/pull/764

AF-547: VFS commit batch broken
